config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get "users/show" => "users#show"
  get '/users' => "users#index"
  get "users/:id" => "users#show", as: :mypage
  get 'search' => "search#search"
  resources :users,only: [:show,:index,:edit,:update] do
    resources :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	
	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

validates :comment,presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: 'User'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
    has_many :relationships, foreign_key: :following_id , dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  
  has_many :revers_of_relationships, class_name: 'Relationship', foreign_key: :follower_id , dependent: :destroy
  has_many :followers, through: :revers_of_relationships, source: :following
  
  def is_followed_by?(user)
    revers_of_relationships.find_by(following_id: user.id).present?
  end
  
  attachment :profile_image, destroy: false
  validates :introduction,length: {maximum:50} 
  validates :name,length: { in: 2..20 }, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
	before_action :configure_permitted_parameters, if: :devise_controller?
	

	
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
      mypage_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:title, :introduction])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id],book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

    def book_comment_params
    params.require(:book_comment).permit(:comment)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]


  def show
    @books = Book.find(params[:id])
    @user = @books.user
    @book = Book.new
    @book_comment = BookComment.new
    
    
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    @books = Book.all
    @user = current_user
    if @book.save
        redirect_to book_path(@book),notice:"Book was successfully created." 
    else
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
  if @book.user == current_user
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render 'edit'
    end
  end
  end

  def destroy
    @book=Book.find(params[:id])
  if @book.user == current_user
    @book.destroy
  end
    redirect_to books_path
  end
  
   def ensure_correct_user
    @book=Book.find(params[:id])
    @user = @book.user
    unless @user == current_user
      redirect_to books_path
    end
   end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  before_action :authenticate_user!

  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how,@model,@value)
  end
  
  
  private
  
  def match(model, value) 
    if model == 'user'
      User.where(name:value)
    elsif model == 'book'
      Book.where(title:value)
   end
  end
    
  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
   end
  end
  

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  
  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how,model,value)
    case how
      when  'match'
        match(model,value)
      when 'forward'     
      forward(model, value)
      when 'backward'
      backward(model, value)
      when  'partical'
      partical(model,value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.where.not(id: current_user.id)
    @book = Book.new
    @user = current_user
  end
  
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
     render "edit"
    end
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<div class="alart">
      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
</div>

 <%= form_with model: @book, local:true do |f| %>
    <div class="form-group">
      <h4>title</h4>
      <%= f.text_field :title , class:"form-control book_title" %>
    </div>
    <div class="form-group">
       <h4>body</h4>
       <%= f.text_area :body , class:"form-control book_body"%>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
       
        <% if book.favorited_by?(current_user) %>
          <td><%= link_to book_favorites_path(book), method: :delete do %>
              ♥<%= book.favorites.count %> いいね</td>
              <% end %>
          <% else %>
           <td><%= link_to book_favorites_path(book), method: :post do %>
             ♡<%= book.favorites.count %> いいね</td>
            <% end %>
         <% end %>
        <td><%= link_to "#{book.book_comments.count} コメント", book_path(book) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
      	<div class="alart">
            <% if @book.errors.any? %>
              <%= @book.errors.count %>error prohibited this obj from being saved:
              <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% end %>
        </div>
      
  		<%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <h4>title</h4>
          <%= f.text_field :title , class:"form-control book_title" %>
        </div>
        <div class="form-group">
           <h4>body</h4>
           <%= f.text_area :body , class:"form-control book_body"%>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book',class:"btn btn-success" %>
        </div>
      <% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @book %>
    </div>
    
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@user) do %>
            <%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @books.title, book_path(@books) %></td>
          <td><%= @books.body %></td>
          
          <% if @books.favorited_by?(current_user) %>
          <td><%= link_to book_favorites_path(@books.id), method: :delete do %>
              ♥<%= @books.favorites.count %> </td>
              <% end %>
          <% else %>
           <td><%= link_to book_favorites_path(@books.id), method: :post do %>
             ♡<%= @books.favorites.count %> </td>
              <% end %>
          <% end %>
          
            <td>コメント数：<%= @books.book_comments.count %></td>
             <% if @books.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@books), class: "btn btn-sm btn-success edit_book_#{@books.id}" %></td>
              <td><%= link_to 'Destroy', book_path(@books), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@books.id}"%></td>
             <% end %>
            </tr>
      </table>   

         <% @books.book_comments.each do |book_comment| %>
           <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
            <%= link_to "Destroy",book_book_comment_path(book_comment.book.id, book_comment.id), method: :delete, data: { confirm: '本当に消しますか？' },class:"btn btn-danger" %>
             <% end %>
             <br>
         <% end %>

           <%= form_with(model:[@books, @book_comment], local: true) do |f| %>
           <%= f.text_area :comment, size: "80x4",placeholder: "コメント" %>
           <br>
           <%= f.submit "送信" %>
           <% end %>
           
     </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @datas.each do |user| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= link_to user.name ,user_path(user.id)%>
                </th>
                <th>
                    <%=user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    
    <% elsif  @model == "book" %>
    <h2>Books search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%=link_to book.title,book_path(book.id) %>
                </th>
                <th>
                    <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
         <td>
         <% if user.is_followed_by?(current_user) %>
          <%=link_to user_relationship_path(user_id: user ,id: @user), method: :delete do %>
            <button type="button" class="btn btn btn-danger">フォロー解除</button>
          <% end %>
        <% else %>
          <%=link_to user_relationships_path(user), method: :post do %>
          <button type="button" class="btn btn btn-primary">フォロー</button>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
	</tr>
	<tr>
	  <th>Follows</th>
	  <th><%= link_to @user.followings.count,followings_user_path(@user)%></th>
	</tr>
	<tr>
	   <th>Followers</th>
	   <th><%= link_to @user.followers.count,followers_user_path(@user)%></th>
  </tr>
</table>

<div class='row'>
  <% if @user == current_user %>
    <%= link_to '',edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{@user}" %>
  <% else %>
    <% if @user.is_followed_by?(current_user) %>
        <%=link_to user_relationship_path(@user), method: :delete do %>
          <button type="button" class="btn btn btn-danger">フォロー解除</button>
          <% end %>
    <% else %>
        <%=link_to user_relationships_path(@user), method: :post do %>
          <button type="button" class="btn btn btn-primary">フォロー</button>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <%= form_with model:@user, local:true do |f| %>
          <%= render 'layouts/errors', obj: @user %>
             <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control name" %>
             </div>
             <div class="form-group">
                <%= f.label :image %>
                <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
             </div>
            <div class="form-group">
              <%= f.label :introduction %>
              <%= f.text_area :introduction, class: "form-control introduction" %>
            </div>
            <div class="form-group">
              <%= f.submit class: 'btn btn-secondary' %>
            </div>
        <% end %>
    </div>
    
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Follower Users</h1>
        
         <% if @users.count > 0 %>
         
          <table class="table text-center">
            <thead>
              <tr>
                <th>Image</th>
                <th>Name</th>
                <th></th>
                <th></th>
                <th></th>
                <th colspan="5"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.followings.count %></td>
              <td>フォロワー数：<%= user.followers.count %></td>
              <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
              </tr>
              <% end %>
             </tbody>
          </table>
        
        <% else %>
        <p>ユーザーはいません</p>
        <% end %>
  
      </div>
    </div>
</div>

app/views/users/followings.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Follow Users</h1>
        
         <% if @users.count > 0 %>
         
          <table class="table text-center">
            <thead>
              <tr>
                <th>Image</th>
                <th>Name</th>
                <th></th>
                <th></th>
                <th></th>
                <th colspan="5"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.followings.count %></td>
              <td>フォロワー数：<%= user.followers.count %></td>
              <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
              </tr>
              <% end %>
             </tbody>
          </table>
        
        <% else %>
        <p>ユーザーはいません</p>
        <% end %>
  
      </div>
    </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'users/index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>